// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 2
		case r == 33: // ['!','!']
			return 3
		case r == 34: // ['"','"']
			return 4
		case r == 36: // ['$','$']
			return 5
		case r == 38: // ['&','&']
			return 3
		case r == 39: // [''',''']
			return 6
		case r == 40: // ['(','(']
			return 7
		case r == 41: // [')',')']
			return 8
		case r == 42: // ['*','*']
			return 3
		case r == 43: // ['+','+']
			return 3
		case r == 44: // [',',',']
			return 9
		case r == 45: // ['-','-']
			return 10
		case r == 46: // ['.','.']
			return 11
		case r == 47: // ['/','/']
			return 3
		case 48 <= r && r <= 57: // ['0','9']
			return 12
		case r == 58: // [':',':']
			return 13
		case r == 60: // ['<','<']
			return 3
		case r == 61: // ['=','=']
			return 3
		case r == 62: // ['>','>']
			return 3
		case r == 63: // ['?','?']
			return 14
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 101: // ['a','e']
			return 11
		case r == 102: // ['f','f']
			return 15
		case 103 <= r && r <= 115: // ['g','s']
			return 11
		case r == 116: // ['t','t']
			return 16
		case 117 <= r && r <= 122: // ['u','z']
			return 11
		case r == 124: // ['|','|']
			return 3
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 3
		case r == 33: // ['!','!']
			return 3
		case r == 38: // ['&','&']
			return 3
		case r == 42: // ['*','*']
			return 3
		case r == 43: // ['+','+']
			return 3
		case r == 45: // ['-','-']
			return 3
		case r == 47: // ['/','/']
			return 3
		case r == 60: // ['<','<']
			return 3
		case r == 61: // ['=','=']
			return 3
		case r == 62: // ['>','>']
			return 3
		case r == 124: // ['|','|']
			return 3
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 3
		case r == 33: // ['!','!']
			return 3
		case r == 38: // ['&','&']
			return 3
		case r == 42: // ['*','*']
			return 3
		case r == 43: // ['+','+']
			return 3
		case r == 45: // ['-','-']
			return 3
		case r == 47: // ['/','/']
			return 3
		case r == 60: // ['<','<']
			return 3
		case r == 61: // ['=','=']
			return 3
		case r == 62: // ['>','>']
			return 3
		case r == 124: // ['|','|']
			return 3
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 17
		case r == 92: // ['\','\']
			return 18
		default:
			return 4
		}
	},
	// S5
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 19
		case r == 36: // ['$','$']
			return 19
		case r == 45: // ['-','-']
			return 19
		case r == 46: // ['.','.']
			return 19
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 19
		case r == 91: // ['[','[']
			return 20
		case r == 93: // [']',']']
			return 19
		case r == 95: // ['_','_']
			return 19
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 21
		case r == 92: // ['\','\']
			return 22
		default:
			return 6
		}
	},
	// S7
	func(r rune) int {
		switch {
		case r == 41: // [')',')']
			return 23
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 3
		case r == 33: // ['!','!']
			return 3
		case r == 38: // ['&','&']
			return 3
		case r == 42: // ['*','*']
			return 3
		case r == 43: // ['+','+']
			return 3
		case r == 45: // ['-','-']
			return 10
		case r == 46: // ['.','.']
			return 11
		case r == 47: // ['/','/']
			return 3
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case r == 60: // ['<','<']
			return 3
		case r == 61: // ['=','=']
			return 3
		case r == 62: // ['>','>']
			return 3
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		case r == 124: // ['|','|']
			return 3
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 12
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 107: // ['a','k']
			return 11
		case r == 108: // ['l','l']
			return 24
		case 109 <= r && r <= 122: // ['m','z']
			return 11
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 113: // ['a','q']
			return 11
		case r == 114: // ['r','r']
			return 25
		case 115 <= r && r <= 122: // ['s','z']
			return 11
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		default:
			return 26
		}
	},
	// S19
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 19
		case r == 36: // ['$','$']
			return 19
		case r == 45: // ['-','-']
			return 19
		case r == 46: // ['.','.']
			return 19
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 19
		case r == 91: // ['[','[']
			return 20
		case r == 93: // [']',']']
			return 19
		case r == 95: // ['_','_']
			return 19
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 27
		case r == 39: // [''',''']
			return 28
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		case r == 93: // [']',']']
			return 30
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		default:
			return 31
		}
	},
	// S23
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case r == 97: // ['a','a']
			return 32
		case 98 <= r && r <= 122: // ['b','z']
			return 11
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 116: // ['a','t']
			return 11
		case r == 117: // ['u','u']
			return 33
		case 118 <= r && r <= 122: // ['v','z']
			return 11
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 17
		case r == 92: // ['\','\']
			return 18
		default:
			return 4
		}
	},
	// S27
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 34
		default:
			return 27
		}
	},
	// S28
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 35
		default:
			return 28
		}
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		case r == 93: // [']',']']
			return 30
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 19
		case r == 36: // ['$','$']
			return 19
		case r == 45: // ['-','-']
			return 19
		case r == 46: // ['.','.']
			return 19
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 19
		case r == 91: // ['[','[']
			return 20
		case r == 93: // [']',']']
			return 19
		case r == 95: // ['_','_']
			return 19
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 21
		case r == 92: // ['\','\']
			return 22
		default:
			return 6
		}
	},
	// S32
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 114: // ['a','r']
			return 11
		case r == 115: // ['s','s']
			return 36
		case 116 <= r && r <= 122: // ['t','z']
			return 11
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 100: // ['a','d']
			return 11
		case r == 101: // ['e','e']
			return 37
		case 102 <= r && r <= 122: // ['f','z']
			return 11
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 93: // [']',']']
			return 38
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 93: // [']',']']
			return 39
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 100: // ['a','d']
			return 11
		case r == 101: // ['e','e']
			return 40
		case 102 <= r && r <= 122: // ['f','z']
			return 11
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 19
		case r == 36: // ['$','$']
			return 19
		case r == 45: // ['-','-']
			return 19
		case r == 46: // ['.','.']
			return 19
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 19
		case r == 91: // ['[','[']
			return 20
		case r == 93: // [']',']']
			return 19
		case r == 95: // ['_','_']
			return 19
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 19
		case r == 36: // ['$','$']
			return 19
		case r == 45: // ['-','-']
			return 19
		case r == 46: // ['.','.']
			return 19
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 19
		case r == 91: // ['[','[']
			return 20
		case r == 93: // [']',']']
			return 19
		case r == 95: // ['_','_']
			return 19
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
}
